package com.example.demo.model;

public class Jobs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.id
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.job_name
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.description
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.id
     *
     * @return the value of jobs.id
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.id
     *
     * @param id the value for jobs.id
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.job_name
     *
     * @return the value of jobs.job_name
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.job_name
     *
     * @param jobName the value for jobs.job_name
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.description
     *
     * @return the value of jobs.description
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.description
     *
     * @param description the value for jobs.description
     *
     * @mbg.generated Wed Oct 23 23:09:08 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}