package com.example.demo.model;

public class Newusers {
    public Newusers(String username, String password, String userSex) {
        this.username = username;
        this.password = password;
        this.userSex = userSex;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newusers.id
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newusers.userName
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newusers.passWord
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newusers.user_sex
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newusers.nick_name
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newusers.id
     *
     * @return the value of newusers.id
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newusers.id
     *
     * @param id the value for newusers.id
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newusers.userName
     *
     * @return the value of newusers.userName
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newusers.userName
     *
     * @param username the value for newusers.userName
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newusers.passWord
     *
     * @return the value of newusers.passWord
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newusers.passWord
     *
     * @param password the value for newusers.passWord
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newusers.user_sex
     *
     * @return the value of newusers.user_sex
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newusers.user_sex
     *
     * @param userSex the value for newusers.user_sex
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newusers.nick_name
     *
     * @return the value of newusers.nick_name
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newusers.nick_name
     *
     * @param nickName the value for newusers.nick_name
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}