package com.example.demo.mapper;

import com.example.demo.model.Newusers;
import com.example.demo.model.NewusersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewusersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    long countByExample(NewusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int deleteByExample(NewusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int insert(Newusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int insertSelective(Newusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    List<Newusers> selectByExample(NewusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    Newusers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Newusers record, @Param("example") NewusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int updateByExample(@Param("record") Newusers record, @Param("example") NewusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int updateByPrimaryKeySelective(Newusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newusers
     *
     * @mbg.generated Fri Nov 15 15:55:35 CST 2019
     */
    int updateByPrimaryKey(Newusers record);
}